version: '3.9'

services:
  dump1090:
    container_name: dump1090
    image: dump1090
    build:
      context: dump1090
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  gps_publisher:
    container_name: gps_publisher
    image: streampublisher
    build:
      context: StreamPublisher
    devices: 
      - /dev/ttyAMA0
    depends_on: 
      - mqtt
    environment:
      - SR_LOG_LEVEL=INFO
      - SR_INPUT_MODE=SERIAL
      - SR_SERIAL_DEVICE=/dev/ttyAMA0
      - SR_MQTT_HOST=mqtt
      - SR_MQTT_PORT=1883
      - SR_MQTT_CLIENT_NAME=gps_reader
      - SR_MQTT_PUBLISH_TOPIC=/gps/nmea
    restart: unless-stopped

  adsb_publisher:
    container_name: adsb_publisher
    image: streampublisher
    build:
      context: StreamPublisher
    depends_on: 
      - mqtt
      - dump1090
    environment:
      - SR_LOG_LEVEL=INFO
      - SR_INPUT_MODE=TCP
      - SR_TCP_HOST=dump1090
      - SR_TCP_PORT=30003
      - SR_MQTT_HOST=mqtt
      - SR_MQTT_PORT=1883
      - SR_MQTT_CLIENT_NAME=adsb_reader
      - SR_MQTT_PUBLISH_TOPIC=/adsb/sbs
    restart: unless-stopped

  monitor:
    container_name: monitor
    image: monitor
    build:
      context: monitor
    depends_on:
      - mqtt
    environment:
      - MO_LOG_LEVEL=INFO
      - MO_MQTT_HOST=localhost
      - MO_MQTT_PORT=1883
      - MO_MQTT_CLIENT_NAME=monitor
      - MO_MQTT_NMEA_TOPIC=/gps/nmea
      - MO_MQTT_SBS_TOPIC=/adsb/sbs
      - MO_GDL90_BROADCAST_IP=192.168.77.255
      - MO_GDL90_PORT=4000
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    restart: unless-stopped

  accesspoint:
    container_name: accesspoint
    image: accesspoint
    build:
      context: AccessPoint
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
