version: '3.9'

services:
  dump1090:
    container_name: dump1090
    image: dump1090
    build:
      context: dump1090
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  ublox:
    container_name: ublox
    image: ghcr.io/gravity981/easyadsb/ublox
    build:
      dockerfile: Dockerfile.ublox
    devices: 
      - /dev/ttyAMA0
    depends_on: 
      - mqtt
    environment:
      - UB_LOG_LEVEL=INFO
      - UB_SERIAL_DEVICE=/dev/ttyAMA0
      - UB_SERIAL_BAUD=9600
      - UB_MQTT_HOST=mqtt
      - UB_MQTT_PORT=1883
      - UB_MQTT_CLIENT_NAME=ublox
      - UB_MQTT_UBX_PUBLISH_TOPIC /easyadsb/ublox/ubx
      - UB_MQTT_NMEA_PUBLISH_TOPIC /easyadsb/ublox/nmea
    restart: unless-stopped

  dump1090mqtt:
    container_name: dump1090mqtt
    image: ghcr.io/gravity981/easyadsb/dump1090mqtt
    build:
      dockerfile: Dockerfile.dump1090mqtt
    depends_on: 
      - mqtt
      - dump1090
    environment:
      - DU_LOG_LEVEL=INFO
      - DU_TCP_HOST=dump1090
      - DU_TCP_PORT=30003
      - DU_MQTT_HOST=mqtt
      - DU_MQTT_PORT=1883
      - DU_MQTT_CLIENT_NAME=dump1090mqtt
      - DU_MQTT_PUBLISH_TOPIC=/easyadsb/dump1090/sbs
    restart: unless-stopped

  monitor:
    container_name: monitor
    image: ghcr.io/gravity981/easyadsb/monitor
    build:
      dockerfile: Dockerfile.monitor
    depends_on:
      - mqtt
    environment:
      - MO_LOG_LEVEL=INFO
      - MO_MQTT_HOST=localhost
      - MO_MQTT_PORT=1883
      - MO_MQTT_CLIENT_NAME=monitor
      - MO_MQTT_UBX_TOPIC=/easyadsb/ublox/ubx
      - MO_MQTT_UBX_CTRL_TOPIC=/easyadsb/ublox/ubx/ctrl
      - MO_MQTT_SBS_TOPIC=/easyadsb/dump1090/sbs
      - MO_MQTT_BME280_TOPIC=/easyadsb/bme280/json
      - MO_GDL90_BROADCAST_IP=192.168.77.255
      - MO_GDL90_PORT=4000
    network_mode: host

  bme280:
    container_name: bme280
    image: ghcr.io/gravity981/easyadsb/bme280
    build:
      dockerfile: Dockerfile.bme280
    devices: 
      - /dev/i2c-1
    depends_on:
      - mqtt
    environment:
      - BM_LOG_LEVEL=INFO
      - BM_MQTT_HOST=mqtt
      - BM_MQTT_PORT=1883
      - BM_MQTT_CLIENT_NAME=bme280
      - BM_MQTT_PUBLISH_TOPIC=/easyadsb/bme280/json
      - BM_I2C_PORT=1
      - BM_I2C_ADDRESS=0x76

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    restart: unless-stopped

  accesspoint:
    container_name: accesspoint
    image: accesspoint
    build:
      context: AccessPoint
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
