name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

permissions:
  contents: read
  packages: write

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  build:
    runs-on: ubuntu-latest
    needs: [ checks ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: AccessPoint
            name: ghcr.io/gravity981/easyadsb/accesspoint
            file: .
          - context: dump1090
            name: ghcr.io/gravity981/easyadsb/dump1090
            file: .
          - context: .
            name: ghcr.io/gravity981/easyadsb/dump1090mqtt
            file: Dockerfile.dump1090mqtt
          - context: .
            name: ghcr.io/gravity981/easyadsb/monitor
            file: Dockerfile.monitor
          - context: .
            name: ghcr.io/gravity981/easyadsb/ublox
            file: Dockerfile.ublox
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7
          push: true
          tags: ${{ matrix.name }}:${{ env.SHORT_SHA }}
