name: checks

on:
  push:
    branches:
  pull_request:
    branches: [ "main" ]
  workflow_call:
  
permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pynmeagps paho-mqtt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --config=.flake8 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
